language: node_js
node_js:
  - "lts/*"
addons:
  chrome: stable
  sauce_connect:
    username: "roland23"
    access_key: "07fff296-d6de-4137-920a-801d82468aac"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - sudo chmod -R 4755 /opt/google/chrome/chrome-sandbox 
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - npm install
script:
  - npm test